sylius_mollie_plugin_qr_code:
    path: /create-payment
    defaults:
        _controller: sylius_mollie_plugin.controller.action.shop.qr_code_action::createPayment
sylius_mollie_plugin_get_qr_code:
    path: /get-code
    defaults:
        _controller: sylius_mollie_plugin.controller.action.shop.qr_code_action::fetchQrCodeFromOrder
sylius_mollie_plugin_remove_qr_code:
    path: /remove-code
    defaults:
        _controller: sylius_mollie_plugin.controller.action.shop.qr_code_action::removeQrCodeFromOrder
